[package]
name = "vleer"
version = "1.0.0"
description = "A Music app from the Future"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.11", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.14", features = [] }
tauri-plugin-os = "2.0.0-beta.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
rusty_ytdl = "0.7.0"
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11.2"
once_cell = "1.8.0"
id3 = "1.13.0"
anyhow = "1.0"
rodio = "0.17.3"
# discord-rpc-client = "0.4"
discord-ipc-rp = "0.1.1"
symphonia = { version = "0.5.4", features = ["mkv", "vorbis"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]

# [target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
# tauri-plugin-window-state = "0.1.0"
