[package]
name = "vleer"
version = "0.1.2"
description = "Vleer"
authors = ["pandadev", "waradu"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
anyhow = "1.0.95"
discord-rich-presence = "0.2.5"
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.135"
sqlx = { version = "0.8.3", features = [
  "runtime-tokio",
  "tls-native-tls",
  "sqlite",
  "chrono",
] }
log = "0.4.22"
env_logger = "0.11.6"
base64 = "0.22.1"
chrono = "0.4.39"
include_dir = "0.7.4"
tokio = { version = "1.42.0", features = ["full"] }
serde_with = "3.12.0"
rodio = "0.20.1"
once_cell = "1.20.2"

tauri = { version = "2.2.0", features = ["devtools", "unstable"] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-fs = "2.2.0"
tauri-plugin-global-shortcut = "2.2.0"
tauri-plugin-os = "2.2.0"
tauri-plugin-prevent-default = "1.0.1"
tauri-plugin-updater = "2.3.1"
tauri-plugin-aptabase = { git = "https://github.com/aptabase/tauri-plugin-aptabase", branch = "v2" }


[features]
custom-protocol = ["tauri/custom-protocol"]
