[package]
name = "vleer"
version = "0.1.1"
description = "Vleer"
authors = ["pandadev", "waradu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.18", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.23", features = ["devtools", "unstable"] }
tauri-plugin-os = "2.0.0-beta.7"
tauri-plugin-fs = "2.0.0-beta.10"
tauri-plugin-dialog = "2.0.0-beta.10"
tauri-plugin-updater = "2.0.0-beta.9"
tauri-plugin-global-shortcut = "2.0.0-beta.7"
tauri-plugin-window-state = "2.0.0-beta.10"
tauri-plugin-single-instance = "2.0.0-beta.10"
tauri-plugin-sql = {version = "2.0.0-beta.8", features = ["sqlite"] }
serde_json = "1.0"
serde = "1.0"
lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
discord-ipc-rp = "0.1.1"
dotenv = "0.15.0"
reqwest = "0.12.3"
rusty_ytdl = "0.7.2"
regex = "1.10.4"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
