name: "Nightly Builds"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: install frontend dependencies
        run: npm install -g pnpm && pnpm install

      - uses: tauri-apps/tauri-action@v0

      - name: Publish macOS Artifact
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg

      - name: Publish macOS Updater Files
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: updater-files-macos
          path: |
            src-tauri/target/release/bundle/macos/*.app.tar.gz
            src-tauri/target/release/bundle/macos/*.app.tar.gz.sig

      - name: Publish Windows Artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-windows-msi
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Publish Windows Updater Files
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: updater-files-windows
          path: | 
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/msi/*.msi.sig

      - name: Publish Ubuntu Artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: build-ubuntu-deb
          path: src-tauri/target/release/bundle/deb/*.deb
      - uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: build-ubuntu-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage
      - uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: build-ubuntu-rpm
          path: src-tauri/target/release/bundle/rpm/*.rpm

      - name: Publish Ubuntu Updater Files
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: updater-files-ubuntu
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/appimage/*.AppImage.sig
